export const CHANGE_SEARCH_VALUE = 'CHANGE_SEARCH_VALUE';
export const GET_ROBOTS_PENDING = 'GET_ROBOTS_PENDING';
export const GET_ROBOTS_FAILED = 'GET_ROBOTS_FAILED';
export const GET_ROBOTS_SUCCESS = 'GET_ROBOTS_SUCCESS';
